# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 19, 41, 19, 260804), verbose_name='Date of transaction'),
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together=set([]),
        ),
    ]
