# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20170110_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 10, 22, 40, 40, 257173), verbose_name='Date of transaction'),
        ),
    ]
