# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 19:43
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20170110_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 19, 43, 0, 538163, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
