# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 11:04
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20170113_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slug',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 14, 11, 4, 0, 422878, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
