# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:42
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20170120_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 21, 12, 42, 19, 693266, tzinfo=utc), verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
