# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:07
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20170121_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='budgets.Budget'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 22, 20, 7, 53, 111582, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
