# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20170122_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 17, 43, 55, 624167, tzinfo=utc), verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
