# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20170123_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 30, 18, 30, 9, 860502, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
