# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20170123_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 11, 20, 15, 56, 695308, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
