# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('transactions', '0028_auto_20170130_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 4, 11, 42, 58, 948737, tzinfo=utc), verbose_name='Date of transaction'),
        ),
    ]
