# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20170115_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='finishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2017, 1, 16, 16, 53, 1, 73062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2017, 1, 16, 16, 53, 1, 73062, tzinfo=utc)),
        ),
    ]
