# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:42
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20170120_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2017, 1, 21, 12, 42, 19, 693266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2017, 1, 21, 12, 42, 19, 693266, tzinfo=utc)),
        ),
    ]
