# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20170211_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
